<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExtentReports" Version="5.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Microsoft.Playwright.MSTest" Version="1.55.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.10.4" />
    <PackageReference Include="MSTest.TestFramework" Version="3.10.4" />
    <PackageReference Include="NLog" Version="6.0.4" />
    <PackageReference Include="NLog.Extensions.Logging" Version="6.0.4" />
    <PackageReference Include="Reqnroll.MsTest" Version="3.0.2" />
  </ItemGroup>

</Project>
